#!/usr/bin/env python3

import sys


def get_args():
    """ Get command line arguments """

    import argparse
    parser = argparse.ArgumentParser()
    return parser.parse_args()


def main(args):
    """ Entry point for script """
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main(get_args()))
    except KeyboardInterrupt:
        sys.exit(0)
